<script setup lang="ts">
import { computed } from 'vue'
import { useSpoilerStore } from '@/stores/spoiler'
import { readableSize } from '@/lib/maths'
import { commonPrefix } from '@/lib/strings'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import BaseCard from '@/components/common/BaseCard.vue'
import BaseButton from '@/components/common/BaseButton.vue'

const TARGET_SIZE = Math.round(1024 * 1024 * 9.75)
const spoilerStore = useSpoilerStore()

const downloadEnabled = computed(() => spoilerStore.recordings.length > 0)

const formatRecordName = (name: string) => {
  if (name.endsWith('.aoe2record')) {
    name = name.substring(0, name.length - '.aoe2record'.length)
  }

  return `${name}_padded.aoe2record`
}

const paddedSize = computed(() => {
  if (spoilerStore.recordings.length == 0) {
    return 0
  }

  return Math.max(...spoilerStore.recordings.map((recording) => recording.size), TARGET_SIZE)
})

const padFile = (file: File, targetSize: number) => {
  if (file.size > targetSize) {
    return file
  }

  const suffixLen = targetSize - file.size
  const suffixArray = new Uint8Array(suffixLen).fill(0xaa)

  const dummyFile = new Blob([file, suffixArray, new Uint32Array([suffixLen]), 'AOE2_PAD'])
  return dummyFile
}

const downloadPadded = (file: File) => {
  console.log('download padded', file.size, paddedSize.value)
  const paddedRecording = padFile(file, paddedSize.value)
  return saveAs(paddedRecording, formatRecordName(file.name))
}

function downloadZip() {
  const zip = new JSZip()
  const zipComment = 'Generated by https://replaypacker.zeta-two.com'

  const targetSize = paddedSize.value

  for (const recording of spoilerStore.recordings) {
    const paddedRecording = padFile(recording, targetSize)
    zip.file(formatRecordName(recording.name), paddedRecording)
  }

  // TODO: This is a bit hacky but works for now
  let zipName =
    commonPrefix(spoilerStore.recordings.map((recording) => recording.name)) ||
    'padded-recordings.zip'
  if (zipName.endsWith('_G')) {
    zipName = zipName.substring(0, zipName.length - 2)
  }

  zip
    .generateAsync({
      type: 'blob',
      comment: zipComment,
      compression: 'DEFLATE',
      compressionOptions: {
        level: 6
      }
    })
    .then(function (blob) {
      saveAs(blob, zipName)
    })
}
</script>

<template>
  <BaseCard spacing="top" :class="$style.cardSpacing">
    <table :class="$style.table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Size</th>
          <th>Padded size</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>All replays</td>
          <td></td>
          <td></td>
          <td>
            <BaseButton variant="primary" :disabled="!downloadEnabled" @click="downloadZip">
              Download
            </BaseButton>
          </td>
        </tr>
        <tr v-for="recording in spoilerStore.recordings" :key="recording.name">
          <td>{{ formatRecordName(recording.name) }}</td>
          <td>{{ readableSize(recording.size) }}</td>
          <td>{{ readableSize(paddedSize) }}</td>
          <td>
            <BaseButton
              variant="primary"
              :disabled="!downloadEnabled"
              @click="downloadPadded(recording)"
            >
              Download
            </BaseButton>
          </td>
        </tr>
      </tbody>
    </table>
  </BaseCard>
</template>

<style module>
.cardSpacing {
  margin-bottom: var(--space-4);
}
.table {
  border-collapse: collapse;
}
.table th,
.table td {
  border: 1px solid var(--color-border-default);
  padding: var(--space-1);
}
</style>
